### ISSUE TITLE
Uknown Named Module: 'react/lib/NativeMethodMixin'

### ISSUE THREAD

**Issue by fawwaz** [shoutem/ui#101]
I follow the installation step (`npm install` & `react-native link`), but everytime I want to import a component from `@shoutem/ui` it throws an exception Unknown Named Module : 'react/lib/NativeMethodMixin'

whats wrong ?

**Comment by SoHotSoup** [comment]
This is already fixed by: https://github.com/shoutem/ui/issues/93, could you check which version of `@shoutem/animation` you have installed? Make sure that npm resolved it as `0.8.10`.
We will release new version of `@shoutem/ui` that has `@shoutem/animation@0.8.10` as dependency soon.

Thank you for submitting this issue. Please close it if my answer was useful to you.
