### ISSUE TITLE
Styles/font not working 100%

### ISSUE THREAD

**Issue by benjick** [shoutem/ui#110]
Hey

Finally trying out this toolkit, but everything looks a bit off. I just tried to insert a button using this code:

```jsx
<Button styleName="dark" onPress={this.start}>
  <Icon name="play" />
  <Text>{this.props.text.toUpperCase()}</Text>
</Button>
```

But it looks like this:
![screen shot 2016-12-13 at 11 42 51](https://cloud.githubusercontent.com/assets/430872/21137299/5b982b7c-c129-11e6-9941-5775e4cdc7f6.png)

It's fully wide, not the right black and not the right font. I've tried reinstalling the package but it doesn't help.

I also tried using this:

```jsx
<NavigationBar
  styleName="fade clear"
  centerComponent={<Title>TITLE</Title>}
/>
```

but it doesn't render anything

**Comment by SoHotSoup** [comment]
Hey @benjick! Could I ask you to share your RN versions and more of your code with me?

**Comment by benjick** [comment]
I was importing `Text` from  `react-native` instead of shoutem, that solved the issue with the button.

I also figured out what was wrong with the NavigationBar, but now how to solve it in a nice way. Siblings to `NavigationBar` gets placed on top of it which means I cannot see it. For now I put a marginTop: 64 on the sibling element but that's not nice, is there a good example on how to put up a NavigationBar with content below it?

**Comment by SoHotSoup** [comment]
NavigationBar is positioned `absolute` by default that's why its siblings come below it. There is already PR that will add styleName `inline` to `NavigationBar`
https://github.com/shoutem/ui/pull/104

**Comment by SoHotSoup** [comment]
Can we close this issue now?

**Comment by benjick** [comment]
Hey, didn't wanna open a new issue, but how should one use Navigation bar?

Looking at https://github.com/shoutem/ui/blob/develop/examples/RestaurantsApp/app/RestaurantsList.js#L55-L62 I did this:

```js
Screen>
  <NavigationBar title="All Restaurants" />
  <ListView
    data={[1]}
    renderRow={row => <Item row={row} />}
  />
</Screen>
```

but that puts siblings above it. What's the real way of constructing views with this?

**Comment by SoHotSoup** [comment]
Hey @benjick what `NavigationBar` did you imported?

**Comment by benjick** [comment]
@SoHotSoup I have this:
`import { NavigationBar, Title, ListView, Screen, Text } from '@shoutem/ui';`

It works great with styleName="inline", just curious how I would use it without

**Comment by SoHotSoup** [comment]
@benjick Ok, now I see. The idea of that `NavigationBar` was to be used as navigation bar component for React native's `Navigatior`. So, we internally have used it to pass it to `Navigator` as `renderNavigationBar`. That's why it is by default positioned absolutely because we wanted it to be rendered above the screens. Later we migrated on our variant of `NavigationExperimental` and created `CardStack` which companioned with `NavigationBar` from (@shoutem/ui/navigation) would have a real native look and feel and real navigation bar transitions. In that case, `NavigationBar` is a just virtual component that provides an interface to set Navigation bar's props dynamically, which is not supported by other navigation libs.
Take a look at Restaurants app on how to use it, and if you have any questions, I will try to address 'em all. 😄

**Comment by SoHotSoup** [comment]
I know we should document and promote this more, and we will do that in following days.

**Comment by benjick** [comment]
Okay that makes sense! Thank you :)
