### ISSUE TITLE
Impossible to pass array to style prop

### ISSUE THREAD

**Issue by gaykov** [shoutem/ui#111]
According to React Native documentation we can pass style prop as an array. Like this:
```javascript
<Text style={[styles.red, styles.bigblue]}>red, then bigblue</Text>
```

But this rule is broken for Shoutem UI components. The following example is not applying any styles to Tile component:
```javascript
<Tile  style={[styles.container, !this.props.data.isActive && styles.expired]}>
...
</Tile>
```  

Thanks!

**Comment by ikalafat** [comment]
Hi @gaykov,

Use ... (spread operator) instead of array.
````

const resolvedStyle = !this.props.data.isActive && styles.expired;

and then in component you can do it like below 
<Tile style={{ ...styles.container, ...resolvedStyle}} >
...
</Tile>
```

**Comment by gaykov** [comment]
Thanks @ikalafat. I'm using similar solution currently. But I think that it should be consistent with ReactNative.

**Comment by SoHotSoup** [comment]
@gaykov thank you for using our toolkit. We were thinking about supporting array styles, but it would have a large impact on performance because merge of styles across the theme then becomes more complex. So in advance of supporting style nesting and overriding through the theme, we don't support style arrays and styles created with `StyleSheet.create` for now. I see this as the great value for a small price. 😉

**Comment by gaykov** [comment]
@SoHotSoup yeah, it definitely makes sense. Thank you for explanation!
