### ISSUE TITLE
Lightbox: The prop 'onRequestClose' is marked required in the 'Modal'

### ISSUE THREAD

**Issue by brandon-dewitt** [shoutem/ui#137]
Looks like this was fixed in the react-native-lightbox module.  Can the change be pulled into your fork?

https://github.com/oblador/react-native-lightbox/commit/c84a8543d4511fe6a44c3d7820747c9c1bddd875

**Comment by rsekulic1** [comment]
@brandon-dewitt Thank you for submitting the issue and sorry for a late response. We're currently working on fixing the majority of the issues and we will release a new version of `@shoutem/ui` hopefully next week with the fix included.

**Comment by martinezguillaume** [comment]
There is a pr here https://github.com/oblador/react-native-lightbox/pull/51 since august 2016... Seems that the repo is dead...

To temporary fix the warning you can manually add onRequestClose={() => null} on line 218 in LightboxOverlay.js (issue https://github.com/oblador/react-native-lightbox/issues/46)

**Comment by brandon-dewitt** [comment]
@rsekulic1 thanks!
