### ISSUE TITLE
<Image /> with png source

### ISSUE THREAD

**Issue by ng-hai** [shoutem/ui#173]
I use a .png image for Shoutem UI Image tag, but it's not transparent completely.

![simulator screen shot feb 23 2017 4 25 29 pm](https://cloud.githubusercontent.com/assets/19520278/23252815/ba967eb4-f9e4-11e6-8485-ff9e5ac40cb2.png)

Then I change to React Native Image tag; it works correctly.

![simulator screen shot feb 23 2017 4 27 16 pm](https://cloud.githubusercontent.com/assets/19520278/23252888/fbb00d5c-f9e4-11e6-91f9-724c267247e8.png)

**Comment by SoHotSoup** [comment]
Hey @ng-hai, it seems to me that our Image has a background by default. https://github.com/shoutem/ui/blob/develop/theme.js#L332

I would check with designers is this by design and why it is like that. For now you can override the background style:
```javascript
<Image style={{ backgroundColor: 'rgba(0,0,0,0)' }} />
```

Or if you want to contribute, maybe it would be useful to define some styleName to image:
```javascript
'.transparent': {
  backgroundColor: 'rgba(0,0,0,0)',
}
```

Maybe it's event cool to add it to commonVariants style:
https://github.com/shoutem/ui/blob/develop/theme.js#L78

Thank you!
