### ISSUE TITLE
Title & SubTitle loose default theme styles

### ISSUE THREAD

**Issue by rakeshgajula** [shoutem/ui#187]
Hi,

I am trying to use StyleProvider with the following snippet

            <StyleProvider style={theme}>
                <View style={{flex: 1}}>
                    <LinearGradient colors={[
                        "#164d8d",
                        "#2172d0"]}  style={{width: null, height: 70}} >
                        <NavigationBar styleName="fade clear"
                            centerComponent={<Text>HOME</Text>}
                        />              
                    </LinearGradient>
                </View>
            </StyleProvider>

The theme is empty 
const theme = {

};

Following is the result

![image](https://cloud.githubusercontent.com/assets/1473945/23737316/46b4f404-0460-11e7-90b3-c0c524fe2f2e.png)

If i remove the StyleProvider things look normal.

Am I missing something ?

Thanks

**Comment by SoHotSoup** [comment]
The problem is that you are providing the theme that doesn't define style for any component. If you want to override style for any component I would suggest to you to import our theme and merge your custom style with it, and provide that resulting style to `StyleProvider`.
Btw, you don't need to wrap `NavigationBar` with `LinearGradient` if you pass `fade` `styleName` to `NavigationBar`.

**Comment by rakeshgajula** [comment]
Thanks for the Reply.

I did the following 
`
import {getTheme} from "@shoutem/ui";

const theme = _.merge(getTheme(), {
    "shoutem.ui.SomeComponent" : { backgroundColor: "red" },
});

<StyleProvider theme={theme}>
  <View></View>
</StyleProvider>
`

I do not get the default styles.

I went through previous discussions but no luck.

Thanks
Rakesh

**Comment by zrumenjak** [comment]
This should work. Could you include a better example of your code, so that I can see how are you passing this theme to the `StyleProvider`?
