### ISSUE TITLE
Increase the Navbar centerComponent Width

### ISSUE THREAD

**Issue by mosesmc52** [shoutem/ui#192]
For the Navbar object how do I increase the width of the center component. Currently the width displays on 2 lines, I want it to display on a single line. 

![screen shot 2017-03-14 at 1 47 32 pm](https://cloud.githubusercontent.com/assets/5233925/23917288/c9eceb82-08bc-11e7-9426-bd2485047441.png)

**Comment by zrumenjak** [comment]
The `Title` component has `numberOfLines` set to 1, so this shouldn't happen (https://github.com/shoutem/ui/blob/develop/components/NavigationBar/composeChildren.js#L13).

Which `NavigationBar` are you using? There are two, the one from `@shoutem/ui`, and the one from `@shoutem/ui/navigation`. Could you include a code snippet so that I can see how are you rendering this title.
