### ISSUE TITLE
Android app returning response error code 500

### ISSUE THREAD

**Issue by leongwq** [shoutem/ui#210]
The example is fine if i ran it on iOS but on android, I'm getting this error

The development server returned response error code: 500

```
URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"from":"C:\\Users\\WQ\\Documents\\Exceptions\\Projects\\Quido\\RN\\Quido\\index.android.js","to":"@shoutem/ui","message":"Unable to resolve module `@shoutem/ui` from `C:\\Users\\WQ\\Documents\\Exceptions\\Projects\\Quido\\RN\\Quido\\index.android.js`: Module does not exist in the module map or in these directories:\n  C:\\Users\\WQ\\Documents\\Exceptions\\Projects\\Quido\\RN\\Quido\\node_modules\\@shoutem\n,   C:\\Users\\WQ\\node_modules\\@shoutem\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
onResponse
    DevServerHelper.java:332
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

```

**Comment by zrumenjak** [comment]
I cannot reproduce this on Mac OS X , we will try to reproduce it on Windows, as it looks like that you are running Windows.

Where did you get the error from the issue? Is this something from the red screen in the app? Also, which version of Windows are you using, and are you testing on an emulator or a real device?

**Comment by ikatun** [comment]
@leongwq Try running `npm install @shoutem/ui && react-native link` instead of `react-native install @shoutem/ui` and `react-native link @shoutem/ui`.

You might encounter a permission error during the build after this. This issue is described here: https://github.com/facebook/react-native/issues/11288.
If that happens, just kill the packager as soon as it runs, run it manually when build is completed (`react-native start` in the project directory) and reload the app on the android device.
