### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.Animated.ScrollView.propTypes')

### ISSUE THREAD

**Issue by uc-asa** [shoutem/ui#212]
Hello Team,
 I have installed npm install --save @shoutem/ui in my project. clean and rebuild project and access import { Tile } from '@shoutem/ui' then it generates error
undefined is not an object (evaluating '_reactNative.Animated.ScrollView.propTypes')

![image](https://cloud.githubusercontent.com/assets/16412197/24521471/e2f87b10-15a9-11e7-8073-b2331806abaf.png)

Any suggestion?.

**Comment by zrumenjak** [comment]
I cannot reproduce this on an new RN project.

This is probably caused by because you don't have support for native animations linked in your project (RCTAnimation lib). This lib should be linked by default on newer RN versions, you can find instructions on how to link it manually here: https://github.com/facebook/react-native/issues/11094#issuecomment-263240420.

Please try to link this library, and let me know if this fixes your issue.

**Comment by Taimoor3059** [comment]
hi, I am running into a similar problem where i need to link the RCTAnimation to my project but I just cant seem to figure it out.  i am using a windows 10, android studio, and just recently download react native so i should have a latest version. I imported a Calendar from github and it works fine but when i try to use the Agenda it doesnt work and gives me the RCTAnimation error.
