### ISSUE TITLE
Android sample App performance issue

### ISSUE THREAD

**Issue by devhyunjae** [shoutem/ui#31]
Test Phone
Galaxy S6

I have just followed the ui toolkit introduction.

http://shoutem.github.io/docs/ui-toolkit/introduction

put the example component in `index.android.js`

```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Examples } from '@shoutem/ui';

class HelloWorld extends Component {
  render() {
    return (
      <Examples />
    );
  }
}

AppRegistry.registerComponent('HelloWorld', () => HelloWorld);
```

And when i first run this sample app, it takes about 5~10 secs to render the Examples Component.(<- This time is after js bundle upload completed)

After that, if i touch something from the dropdown, it responses after 5~10 secs to re-render the new components.

Is it because the Example Component is heavy? or is my phone is the problem?(Other RN Apps is fast) or other problem?

**Comment by SoHotSoup** [comment]
Thank you for a detailed report!
Example Component is pretty heavy because it contains all variants of all components, but it doesn't take that much to render it on iPhone, we should inspect that. Could you try RestaurantsApp example on your phone and tell us about its performance? That should be a more realistic usage of the UI toolkit.

**Comment by devhyunjae** [comment]
Yeah it is better, but still not fully satisfied with the performance than pure rn component with custom styling. But this is good repo 😄

**Comment by SoHotSoup** [comment]
Thank you! We are working hard to improve the performance on Android... :)
