### ISSUE TITLE
`UNMET PEER DEPENDENCY react@16.0.0-alpha.12` in react native 0.45.1

### ISSUE THREAD

**Issue by JoshYuJump** [shoutem/ui#320]
I am installed shoutem ui in react native 0.45.1 and get some warnings.

```
└── UNMET PEER DEPENDENCY react@16.0.0-alpha.12

npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-test-renderer@15.4.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN @shoutem/ui@0.21.3 requires a peer of react@^15.0.0 but none was installed.
npm WARN @shoutem/animation@0.11.0 requires a peer of react@^15.0.0 but none was installed.
npm WARN @shoutem/theme@0.10.0 requires a peer of react@^15.1.0 but none was installed.
```

**Comment by Vladimir-Vdovic** [comment]
It's a semver quirk that the community hasn't settled on yet. The thing is that "react": "16.0.0-alpha.12", doesn't match peer dependency requirement "~15.4.0" or "~15.0.0". The issue lies in "-alpha.6" suffix which is treated differently in semver resolution algorithm. You can read about it here: https://github.com/npm/node-semver#prerelease-tags. You can safely ignore those warnings.
