### ISSUE TITLE
HelloWorld crashing: __DEV__ is not defined

### ISSUE THREAD

**Issue by aessig** [shoutem/ui#50]
Just trying to use the example that you put in the readme and hit that error: 
`TransformError: /Users/username/Project/node_modules/@shoutem/ui/index.js: __DEV__ is not defined` Any idea how to fix this ?

**Comment by nillo** [comment]
i have the same issue when adding ui components to my project, 
im running on     "react-native": "^0.34.0",  and trying it on IOS, 

i tried to add

`import {
  DropDownMenu
} from '@shoutem/ui';`

with some example code: 
```
<DropDownMenu
          options={[
            {
              name: 'Lifestyle',
              id: '7',
            },
            {
              name: 'Lifestyle',
              id: '7',
            },
            {
              name: 'Food',
              id: '8',
            },
            {
              name: 'Food',
              id: '8',
            },
            {
              name: 'Nature',
              id: '9',
            },

          ]}
          titleProperty={"name"}
          valueProperty={"id"}
        />
```

i get the following error: (don't mind the folder blank space, i edited the picture)
![Image of Error](https://s17.postimg.org/9cudp02fj/error.png)

The errors shows, when the app is starting, (the packager gets stuck at 98%, but i guess that is because of the script error)

while installing with these commands:
```
$ npm install --save @shoutem/ui
$ react-native link
```

I got these errors, i don't know if they are related to the issue:
```
{ [Error: Cannot find module '/Users/xxx/Development/xxx/node_modules/@shoutem/ui/node_modules/lodash/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/xxx/Development/xxx/node_modules/@shoutem/ui/node_modules/react-native-vector-icons/package.json'] code: 'MODULE_NOT_FOUND' }
```

**Comment by nillo** [comment]
Well i got it to work, but it feels kinda hacky. 
these where the steps i had to take to fix it:

- npm uninstall  @shoutem/ui
-npm i babel-preset-react-native --save-dev (https://github.com/facebook/react-native/issues/7814)

create a .babelrc, in the project root
```
{
  "presets": ["react-native"]
}
```

which is kinda weird, because, because the preset: react-native, is the default preset, that would be used without babel-preset-react-native, but i guess it does some magic under the hood.

anyways, after installing this, shoutem complained, that it could not find string_decoder , so i installed it to the root, so all dependencies can use it, after i installed it, string_decoder complained it could not find buffer, then i installed buffer so

```
- npm install string_decoder
- npm install buffer

```
after that , my app was able to start, but it complained that it could not find Rubik-regular.ttf,
so i manually had to copy the Bundle Resources (Rubik-icon-font.ttf and all Rubik-XXX.ttf fonts)
and also to manually add them to the Info.plist

Fonts provided by application [array]

so:
```
- Copy Bundle Resources (all fonts from the node_modules/@shoutem/ui/fonts folder.
- Add all fonts to info.plift -> Fonts provided by application

```


I still have to do all this for android,  which is always more cluncky, so i hope with all this information we can come to a solution :)

**Comment by aessig** [comment]
Yes, just did the same hacky install of babel-preset to make it work

**Comment by SoHotSoup** [comment]
Thank you both, we didn't experience this issue while testing the last release. So it might be related to different `babel` versions. Could you, please, print out yours? What seems to me is that `.babelrc` file under `@shoutem/ui` is making the troubles here. We will take a look at this, and, I hope, fix it.

**Comment by ikalafat** [comment]
@SoHotSoup, I think that Goran and I have encountered similar (probably related) `TransformError` issue, caused by `.babelrc`.

1. Pull shoutem/ui
2. `cd examples/RestaurantApp`
3. `npm install`
4. `react-native start`

After fetching the package in application, redbox with TransformError message appears.

Quick fix was to delete `.babelrc` file from `ui` folder, and restart packager.

**Comment by nillo** [comment]
removing the .babelrc from the ui folder was idd the idd, i re-did the whole process. and the __DEV__ error was gone. It still asked me for string_decoder and buffer.

which brings me to this error:
```
{ [Error: Cannot find module '/Users/xxx/Development/xxx/node_modules/@shoutem/ui/node_modules/lodash/package.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module '/Users/xxx/Development/xxx/node_modules/@shoutem/ui/node_modules/react-native-vector-icons/package.json'] code: 'MODULE_NOT_FOUND' }
```

In your package .json u have lodash, and react-native-vector icons, as a dependency, though my project already uses lodash, and react-native-vector-icons.

so they are available here:
```
'/Users/xxx/Development/xxx/node_modules/lodash
'/Users/xxx/Development/xxx/node_modules/react-native-vector-icons
```

So they won't be installed as a dependency specific to your project, and this is where the linking fails. so i still have to do all the linking myself (e.g fonts within my info.plist, and copy the bundling resources)

- why string_decoder / and buffer are not being installed is  still a mystery to me.

**Comment by nillo** [comment]
> So it might be related to different babel versions. Could you, please, print out yours? 
i just use the latest babel that comes with react-native 0.34

```
    "babel-core": "^6.10.4",
    "babel-plugin-external-helpers": "^6.8.0",
    "babel-plugin-syntax-trailing-function-commas": "^6.5.0",
    "babel-plugin-transform-flow-strip-types": "^6.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.6.5",
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015-node": "^6.1.0",
    "babel-preset-fbjs": "^2.0.0",
    "babel-preset-react-native": "^1.9.0",
    "babel-register": "^6.6.0",
    "babel-types": "^6.6.4",
```

this is in their package.json ,within the react-native folder within my node-modules folder
